apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mongo-deployment
  labels:
    app: go-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mongo
  template:
    metadata:
      labels:
        app: go-mongo
    spec:
      containers:
        - name: go-mongo
          image: carlosngv/so1-go-mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: MONGO_ADDRESS
              value: "mongodb://so1-mongodb:D6KMglupcEagiKMis6Fff213MAD63Yz3VNAxghsdIyQqADe6ch21EMfovPV9a2DlT0cXKzjb2gjvACDbbmd6HA==@so1-mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@so1-mongodb@"
---
apiVersion: v1
kind: Service
metadata:
  name: go-mongo-service
spec:
  selector:
      app: go-mongo
  type: LoadBalancer
  ports:
    - port: 9001
      protocol: TCP
