apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: gcr.io/so1-proyecto-g17/grpc-client:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
          env:
            - name: GRPC_SERVER_ADDRESS
              value: "grpc-server-service"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
spec:
  selector:
      app: grpc-client
  type: LoadBalancer
  ports:
    - port: 8200
      protocol: TCP
